### ISSUE TITLE
Support AIX as target

### ISSUE THREAD

**Issue by cheeseplus** [chef/chef-apply#38]
Moving on behalf of @sclark007 https://github.com/chef/chef-workstation/issues/237

Can we get some AIX love please 

## Description
CHEFTARG001

'aix' is not a supported target operating system at this time.

We plan to support a range of target operating systems,
but during this targeted beta we are constraining our efforts
to Windows and Linux.

If you are not able to resolve this issue, please contact Chef support
at beta@chef.io

## Chef Workstation Version
latest stable release 

## Platform Version
AIX 7.1

**Comment by tyler-ball** [comment]
Triaging issues - we don't have a timeline for this but it is something we want to do

**Comment by vkarve-chef** [comment]
work is completed, this will be available in next workstation release.
