### ISSUE TITLE
Support non-omnibus chef-client installs

### ISSUE THREAD

**Issue by cheeseplus** [chef/chef-apply#39]
## Description
In the event that chef-client isn't installed via Omnibus, try to discover and use a working `chef-client` if in a reasonable system location.

- rvm/rbenv/chruby installs are likely not easily supported

## Replication Case

https://github.com/chef/chef-workstation/issues/185

**Comment by tyler-ball** [comment]
Unfortunately with the time the Workstation team has, we are going to focus our efforts on installing / managing Chef Client via supported paths (Omnibus, Habitat).
