### ISSUE TITLE
Support macOS as target

### ISSUE THREAD

**Issue by cheeseplus** [chef/chef-apply#42]
## Description

Support targets of macOS

### Replication Case

At present this breaks on:
1. grabbing the installer
2. creating remote_path (tmpdir)
3. executing chef-client

### Client Output

```
chef-run -i ~/.ssh/id_rsa --user "user" ssh://grimoire log boop
[✔] Packaging cookbook... done!
[✔] Generating local policyfile... exporting... done!
[✖] Applying log[boop] from resource to target.
└── [✖] [grimoire] ChefApply::TargetHost::UnsupportedTargetOS

CHEFTARG001

'mac_os_x' is not a supported target operating system at this time.
```

## Acceptance Criteria

The following command will create a directory on a macOS host: `chef-run SOMEUSER:SOME_PASSWORD@A_MAC_HOST directory /tmp/foo`

**Comment by tyler-ball** [comment]
Triaging issues - we don't have a timeline for this but it is something we want to do

**Comment by tas50** [comment]
Anyone taking this on should check out the previous PR. It won't rebase due to changes in the codebase, but the overall implementation is sound.

**Comment by nikhil2611** [comment]
Fixed.
