### ISSUE TITLE
Can't pass symbols for ad-hoc resource property values

### ISSUE THREAD

**Issue by KrisShannon** [chef/chef-apply#52]
## Description

Many resources use symbols for property values and don't auto-convert strings.

## Chef Apply Version

```
% chef-run --version                                                                               
chef-run: 0.2.0
```

## Replication Case

An example is the guard_interpreter property
`chef-run user@host directory /tmp/test guard_interpreter=perl only_if='my $var; exit 0'`

## Client Output

```
A property value you provided is not valid:

  Option guard_interpreter must be a kind of [Symbol]!  You passed "perl".
```

**Comment by tyler-ball** [comment]
Thanks @KrisShannon - I think we could make this an easy fix by allowing users to specify `guard_interpreter=:perl` or `guard_interpreter=":perl"` and we convert that to a symbol instead of a string internally

**Comment by tas50** [comment]
This fix will go out in this weeks Chef Workstation
