### ISSUE TITLE
Chef run could use the habitat based chef-client if installed

### ISSUE THREAD

**Issue by TheLunaticScripter** [chef/chef-apply#91]
### Describe the Enhancement:
Currently, under the effortless_config model, the chef-client is installed using habitat. To avoid having multiple versions of the chef-client installed. It would be nice if the chef-run was also able to detect that a habitat base version of the client was installed on the system and use it to run the cookbook. 

### Describe the Need:
This would allow customers who are using the effortless pattern to use habitat to manage the chef-client version on the system and also use chef run.

### Current Alternative
This isn't really a huge problem as both tools can work independently of each other this is more a nice to have.

### Can We Help You Implement This?:
I need to see where this fits on the priorities list but happy to help if needed. There is probably a larger strategic discussion that this is part of but not an immediate need.

**Comment by afiune** [comment]
Thank you for filling this Issue @TheLunaticScripter - We agree with the way you are phrasing this enhancement and would love to have it on future release(s), we will prioritize this work accordingly.

**Comment by tas50** [comment]
I'm going to close this one as being outside the scope right now. Since we want to support all platforms that omnibus runs on we can't use the effortless packages.
